# Generated by Django 5.0.6 on 2024-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circularproduct',
            name='circular',
        ),
        migrations.RemoveField(
            model_name='circularproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Circular',
        ),
        migrations.DeleteModel(
            name='CircularProduct',
        ),
    ]
