# Generated by Django 5.0.6 on 2024-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_circularproduct_circular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_v',
            field=models.IntegerField(default=1),
        ),
    ]
