# Generated by Django 5.0.7 on 2024-07-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_product__v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
    ]
