# Generated by Django 5.0.7 on 2024-07-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=80)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=500)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'market_id', 'address'], name='comparisons_name_8d3080_idx')],
                'unique_together': {('name', 'market_id', 'address')},
            },
        ),
    ]
