version: '3.8'

services:
  barilo-web:
    build: 
      context: ./services/barilo-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  barilo-api:
    build:
      context: ./services/barilo-api
      dockerfile: Dockerfile
    ports:
      - "1500:1500"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  barilo-mongo-db:
    container_name: barilo-mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: barilo

  barilo-mongo-express:
    container_name: barilo-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: barilo
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false