services:
  # barilo-web:
  #   container_name: barilo-web
  #   build:
  #     context: ./services/barilo-nextjs-chat-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development

  barilo-api:
    build:
      context: ./services/barilo-api
      dockerfile: ./build/rest-server/Dockerfile
    ports:
      - 9234:9234
      - 2223:2223
    depends_on:
      - vault
      - postgres

  postgres:
    container_name: barilo-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: barilo
      POSTGRES_PASSWORD: barilo
      POSTGRES_DB: barilo
    volumes:
      - .pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "barilo"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - 9090:9090
    volumes:
      - ./services/barilo-api/docs/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./services/barilo-api/docs/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  vault:
    container_name: barilo-vault
    image: vault:1.12.4
    ports:
      - 8300:8300
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"

volumes:
  prom_data:
