services:
  barilo-rest-api:
    container_name: barilo-rest-api
    build:
      context: ./services/barilo-rest-api
      dockerfile: ./build/rest-server/Dockerfile
      target: local
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./services/barilo-rest-api:/src
    env_file:
      - ./services/barilo-rest-api/.env

  barilo-web:
    container_name: barilo-web
    build:
      context: ./services/barilo-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/barilo-web:/app

  nginx:
    container_name: barilo-nginx
    image: nginx:latest
    ports:
      - "9234:80"
    volumes:
      - ./services/barilo-api-gateway/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - barilo-rest-api
      - barilo-web

  # barilo-core:
  #   build:
  #     context: ./services/barilo-core
  #     dockerfile: ./build/rest-server/Dockerfile
  #   ports:
  #     - 9234:9234
  #     - 2223:2223
  #   depends_on:
  #     - vault
  #     - postgres

  postgres:
    container_name: barilo-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: barilo
      POSTGRES_PASSWORD: barilo
      POSTGRES_DB: barilo
    volumes:
      - .pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "barilo"]
      interval: 30s
      timeout: 10s
      retries: 3

  # prometheus:
  #   image: prom/prometheus:v2.52.0
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./services/barilo-api/docs/prometheus.yml:/etc/prometheus/prometheus.yml

  # jaeger:
  #   image: jaegertracing/all-in-one:1.57
  #   ports:
  #     - 16686:16686

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.100.0
  #   command: ["--config=/etc/otel-collector.yaml"]
  #   volumes:
  #     - ./services/barilo-api/docs/otel-collector.yaml:/etc/otel-collector.yaml
  #   ports:
  #     - 4317:4317

  # vault:
  #   container_name: barilo-vault
  #   image: vault:1.12.4
  #   ports:
  #     - 8300:8300
  #   cap_add:
  #     - IPC_LOCK
  #   environment:
  #     VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
  #     VAULT_DEV_ROOT_TOKEN_ID: "myroot"

  redis:
    container_name: barilo-redis
    image: redis:6.2.5
    ports:
      - 6379:6379

  rabbitmq:
    container_name: barilo-rabbitmq
    image: rabbitmq:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: barilo
      RABBITMQ_DEFAULT_PASS: barilo

volumes:
  prom_data:
