version: '3.8'

services:
  barilo-web:
    build: 
      context: ./services/barilo-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  barilo-api:
    build:
      context: ./services/barilo-api
      dockerfile: Dockerfile
    ports:
      - "1500:1500"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}