# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: productranking.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14productranking.proto\"\\\n\x0eProductRanking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0btitle_index\x18\x02 \x01(\t\x12\x14\n\x0cweight_index\x18\x03 \x01(\t\x12\x13\n\x0b\x62rand_index\x18\x04 \x01(\t\"M\n\x0bListRequest\x12\x13\n\x0btitle_index\x18\x01 \x01(\t\x12\x14\n\x0cweight_index\x18\x02 \x01(\t\x12\x13\n\x0b\x62rand_index\x18\x03 \x01(\t\"9\n\x0cListResponse\x12)\n\x10product_rankings\x18\x01 \x03(\x0b\x32\x0f.ProductRanking\"L\n\x11\x43reateItemRequest\x12\x1a\n\x12product_ranking_id\x18\x01 \x01(\x05\x12\x1b\n\x13\x63ircular_product_id\x18\x02 \x01(\x05\"5\n\x12\x43reateItemResponse\x12\x1f\n\x17product_ranking_item_id\x18\x01 \x01(\x05\x32w\n\x15ProductRankingService\x12%\n\x04List\x12\x0c.ListRequest\x1a\r.ListResponse\"\x00\x12\x37\n\nCreateItem\x12\x12.CreateItemRequest\x1a\x13.CreateItemResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTRANKING']._serialized_start=24
  _globals['_PRODUCTRANKING']._serialized_end=116
  _globals['_LISTREQUEST']._serialized_start=118
  _globals['_LISTREQUEST']._serialized_end=195
  _globals['_LISTRESPONSE']._serialized_start=197
  _globals['_LISTRESPONSE']._serialized_end=254
  _globals['_CREATEITEMREQUEST']._serialized_start=256
  _globals['_CREATEITEMREQUEST']._serialized_end=332
  _globals['_CREATEITEMRESPONSE']._serialized_start=334
  _globals['_CREATEITEMRESPONSE']._serialized_end=387
  _globals['_PRODUCTRANKINGSERVICE']._serialized_start=389
  _globals['_PRODUCTRANKINGSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
