# Generated by Django 5.0.6 on 2024-05-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='expiration_date',
            field=models.DateField(default='2024-02-01'),
            preserve_default=False,
        ),
    ]
