import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import cn from "classnames";

import { ThemeProvider } from "@/layouts/theme-provider";

const dm = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={cn(
          "min-h-screen bg-muted text-foreground font-sans antialiased",
          dm.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
