# Generated by Django 5.0.6 on 2024-05-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productranking',
            name='description',
        ),
        migrations.AddField(
            model_name='productranking',
            name='title',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
