# Generated by Django 5.0.6 on 2024-05-27 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circular",
            options={"ordering": ["-created_at"]},
        ),
    ]
