# Generated by Django 5.0.6 on 2024-06-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_circular_store_circular_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ForeignKey(default='01J1510ABF28KTX35MB8MZAFNH', on_delete=django.db.models.deletion.CASCADE, to='markets.market'),
            preserve_default=False,
        ),
    ]
