// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Stores struct {
	ID      uuid.UUID
	Name    string
	Address string
	Phone   pgtype.Text
}
